### PR TITLE
Update RedisService.php

### PR DESCRIPTION
**Pull request by rakekniven**
Redis is trademark name. Corrected spelling. Remarked at Transifex.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by janis91** [comment]
Thanks for your contribution. I cannot merge this PR as long as the tests that fail aren't fixed. Option 1: Could you please update the related test(s). Option2: I will use the proposed changes in an own fix commit later this week.
Thanks!

**Comment by janis91** [comment]
The same applies for the other prs, too.

**Comment by rakekniven** [comment]
Hello @janis91 I have no right to adapt any tests on Travis nor do I know how to fix them.
Could you grant me some rights to look into this?
If not I would select option 2.

**Comment by janis91** [comment]
Fixed in #110

**Pull request closed without merging**
