### PR TITLE
App Store link points directly to app

### PR DESCRIPTION
**Pull request by rakekniven**
Direct hopping to app in store.

Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by janis91** [comment]
Could you please rebase and commit again. Otherwise the build fails :-( Thank You!

**Comment by rakekniven** [comment]
Using GitHub only via webinterface. Does my update work for you?

**Comment by janis91** [comment]
The travis build fails and without success I cannot merge :-/ it‘s because I changed something with travis (fixed codacy) in the meantime and now your commit uses old configuration, that doesn‘t work anymore. I can add your fix in a new commit and add another pull request, but then I‘d have to close this one... I just don‘t want to close your contribution without asking you.

**Comment by rakekniven** [comment]
Please add my change to a commit of yourself.

> I just don‘t want to close your contribution without asking you.

You are a polite man 👍

**Pull request closed without merging**
