### PR TITLE
Remove unused import statements

### PR DESCRIPTION
**Pull request by stweil**
This fixes some recommendations from LGTM.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See https://lgtm.com/projects/g/janis91/ocr/alerts. You can add LGTM as a continuous integration tool at https://lgtm.com/projects/g/janis91/ocr/ci/.

**Comment by stweil** [comment]
@janis91, the Travis CI build failure is unrelated to my pull rquest.

**Comment by stweil** [comment]
Ping?

**Comment by janis91** [comment]
Sorry for the delay. I was and still am working on other projects. But I will try to focus on a small update.. I will come back to this ;-)

**Comment by stweil** [comment]
@janis91, should I rebase and update this pull request and send it again? There are still several alerts from LGTM.

**Pull request closed without merging**
